import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';
import { Capacitor } from '@capacitor/core';
import { TextToSpeech } from '@capacitor-community/text-to-speech';
import { languages, t } from './i18n';

type LanguageContextValue = { lang:string; setLang:(lang:string)=>void; t:(key:Parameters<typeof t>[1])=>string; number:(value:string|number)=>string; speak:(text:string)=>void; languages:typeof languages };
const LanguageContext=createContext<LanguageContextValue|null>(null);
const locales:Record<string,string>={en:'en-IN',hi:'hi-IN-u-nu-deva',mr:'mr-IN-u-nu-deva',bn:'bn-IN-u-nu-beng',ta:'ta-IN',te:'te-IN',gu:'gu-IN-u-nu-gujr',pa:'pa-IN-u-nu-guru'};
const speechLocales:Record<string,string>={en:'en-IN',hi:'hi-IN',mr:'mr-IN',bn:'bn-IN',ta:'ta-IN',te:'te-IN',gu:'gu-IN',pa:'pa-IN'};
const speakText=(text:string,lang:string)=>{const locale=speechLocales[lang]??'en-IN';if(Capacitor.isNativePlatform()){void TextToSpeech.stop().then(()=>TextToSpeech.speak({text,lang:locale,rate:.9,pitch:1,volume:1}));return}if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const speakWithMatchingVoice=()=>{const requestedLanguage=locale.slice(0,2).toLowerCase();const voices=window.speechSynthesis.getVoices();const voice=voices.find(item=>item.lang.toLowerCase()===locale.toLowerCase())??voices.find(item=>item.lang.toLowerCase().startsWith(`${requestedLanguage}-`))??voices.find(item=>item.lang.toLowerCase()===requestedLanguage);const utterance=new SpeechSynthesisUtterance(text);utterance.lang=voice?.lang??locale;utterance.voice=voice??null;utterance.rate=.9;window.speechSynthesis.speak(utterance)};if(window.speechSynthesis.getVoices().length){speakWithMatchingVoice();return}const loadVoices=()=>{window.speechSynthesis.removeEventListener('voiceschanged',loadVoices);speakWithMatchingVoice()};window.speechSynthesis.addEventListener('voiceschanged',loadVoices);window.setTimeout(loadVoices,700)};
export function LanguageProvider({children}:{children:ReactNode}){const [lang,setLang]=useState('en');const value=useMemo(()=>({lang,setLang,t:(key:Parameters<typeof t>[1])=>t(lang,key),number:(value:string|number)=>String(value).replace(/\d+/g,digits=>new Intl.NumberFormat(locales[lang]??'en-IN',{useGrouping:false}).format(Number(digits))),speak:(text:string)=>speakText(text,lang),languages}),[lang]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>}
export function useLanguage(){const value=useContext(LanguageContext);if(!value)throw new Error('useLanguage must be used inside LanguageProvider');return value}
