import { useEffect, useMemo, useState } from 'react';
import { villages as demoVillages } from './data/demo';
import { villageText } from './lib/i18n';
import { useLanguage } from './lib/LanguageContext';
import { alertPreview, getVillages } from './services/api';
import type { Village } from './types';
type View='official'|'public'|'asha'|'demo';
const badge=(risk:string)=>`badge ${risk.toLowerCase()}`;
export default function App(){
 const {lang,setLang,t:tx,number,speak,languages}=useLanguage(); const [view,setView]=useState<View>('official'),[villages,setVillages]=useState<Village[]>(demoVillages),[selected,setSelected]=useState(demoVillages[0]),[offline,setOffline]=useState(false),[queue,setQueue]=useState<any[]>(()=>JSON.parse(localStorage.getItem('jr-asha')||'[]')),[channel,setChannel]=useState('SMS'),[,setNotice]=useState('');
 useEffect(()=>{getVillages(demoVillages).then(setVillages)},[]); useEffect(()=>localStorage.setItem('jr-asha',JSON.stringify(queue)),[queue]);
 const stats=useMemo(()=>({high:villages.filter(v=>v.risk==='HIGH').length,moderate:villages.filter(v=>v.risk==='MODERATE').length,safe:villages.filter(v=>v.risk==='SAFE').length,online:villages.filter(v=>v.online).length}),[villages]);
 const water=(value:string)=>tx(value==='SAFE'?'waterSafe':value==='BOIL WATER'?'waterBoil':'waterChlorine'); const risk=(value:string)=>tx(value==='HIGH'?'riskHigh':value==='MODERATE'?'riskModerate':'riskSafe');
 useEffect(()=>{if(view!=='public')return;const timer=window.setTimeout(()=>speak(`${selected.name}. ${water(selected.water)}. ${selected.water==='SAFE'?tx('safeMessage'):tx('unsafeMessage')}`),350);return()=>window.clearTimeout(timer)},[view,lang,selected.id,selected.water]);
 const nav=(name:View,label:string)=><button className={view===name?'active':''} onClick={()=>setView(name)}>{label}</button>;
 function logSymptom(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setQueue(q=>[...q,{id:Date.now(),symptom:fd.get('symptom'),source:fd.get('source'),quality:fd.get('quality'),at:new Date().toLocaleString()}]);e.currentTarget.reset();}
 function simulate(){ const next=villages.map(v=>v.id===selected.id?{...v,score:42,risk:'HIGH' as const,water:'BOIL WATER'}:v);setVillages(next);setSelected(next.find(v=>v.id===selected.id)!); }
 return <main><header><div className="brand"><Logo/> <span>{tx('brand')}</span><small>{tx('tagline')}</small></div><nav>{nav('official',tx('official'))}{nav('public',tx('public'))}{nav('asha',tx('asha'))}{nav('demo',tx('demo'))}<button className="sos">{tx('sos')}</button></nav><button aria-label="Listen to current health guidance" onClick={()=>speak(`${tx('brand')}. ${tx('hero')}. ${selected.name}. ${water(selected.water)}. ${selected.water==='SAFE'?tx('safeMessage'):tx('unsafeMessage')}`)}>🔊 Listen</button><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value)}>{languages.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select></header>
 {view==='official'&&<section className="page"><div className="hero"><div><p className="eyebrow">{tx('control')}</p><h1>{tx('hero')}</h1><p>{tx('subhero')}</p></div><button className="primary" onClick={()=>{setSelected(villages[0]);setView('demo')}}>{tx('run')}</button></div><div className="grid stats"><Card n={villages.length} label={tx('monitored')}/><Card n={stats.high} label={tx('high')} red/><Card n={stats.moderate} label={tx('moderate')} yellow/><Card n={`${stats.online}/${villages.length}`} label={tx('online')}/></div><section className="panel"><h2>{tx('table')}</h2><div className="table"><div className="thead">{tx('village')} <span>{tx('score')}</span><span>{tx('risk')}</span><span>{tx('water')}</span><span>{tx('action')}</span></div>{villages.map(v=><button className="row" key={v.id} onClick={()=>{setSelected(v);setView('public')}}><strong>{v.name}</strong><span className="score">{v.score}</span><span className={badge(v.risk)}>{risk(v.risk)}</span><span>{water(v.water)}</span><span>{villageText(lang,v.id).action}</span></button>)}</div></section><div className="split"><section className="panel"><h2>{tx('ai')}</h2><p className="big">“{villageText(lang,selected.id).explanation}”</p><ul><li>{tx('dispatch')}</li><li>{tx('boil')}</li><li>{tx('notify')}</li></ul></section><section className="panel"><h2>{tx('modules')}</h2><p>🦟 {tx('vector')}</p><p>☀️ {tx('heatmodule')}</p><p>💉 {tx('vaccineModule')}</p></section></div></section>}
 {view==='public'&&<section className="public page"><p className="eyebrow">{selected.name.toUpperCase()} • {tx('citizen')}</p><div className={`status ${selected.risk.toLowerCase()}`}><p>{tx('score')}</p><strong>{selected.score}<small>/100</small></strong><h1>{selected.water==='SAFE'?tx('safe'):tx('required')}: {water(selected.water)}</h1><p className="public-copy">{selected.water==='SAFE'?tx('safeMessage'):tx('unsafeMessage')}</p></div><div className="grid"><Info title={`🦟 ${tx('mosquito')}`} value={risk(selected.mosquito)}/><Info title={`☀️ ${tx('heat')}`} value={risk(selected.heat)}/><Info title={`💉 ${tx('vaccination')}`} value={tx('check')}/></div><section className="panel"><h2>{tx('guidance')}</h2><div className="guidance"><span>{tx('drink')}</span><span>{tx('cover')}</span><span>{tx('stagnant')}</span><span>{tx('phc')}</span></div></section></section>}
 {view==='asha'&&<section className="page"><div className="hero"><div><p className="eyebrow">{tx('portal')}</p><h1>{tx('offlineTitle')}</h1></div><label className="toggle"><input type="checkbox" checked={offline} onChange={e=>setOffline(e.target.checked)}/> {tx('offline')}</label></div><div className="split"><form className="panel" onSubmit={logSymptom}><h2>{tx('log')}</h2><label>{tx('symptom')}<select name="symptom"><option>{tx('fever')}</option><option>{tx('diarrhea')}</option><option>{tx('vomiting')}</option></select></label><label>{tx('source')}<select name="source"><option>{tx('well')}</option><option>{tx('handpump')}</option><option>{tx('tap')}</option></select></label><label>{tx('quality')}<select name="quality"><option>{tx('clear')}</option><option>{tx('murky')}</option><option>{tx('odor')}</option></select></label><button className="primary">{tx('save')}</button></form><section className="panel"><h2>{tx('queue')} ({queue.length})</h2><p>{tx('last')} {offline?tx('waiting'):tx('justNow')}</p><button className="primary" onClick={()=>{if(offline){setNotice(tx('offline'));return}setQueue([]);setNotice(tx('sync'))}}>{tx('sync')}</button>{queue.slice(-3).map(x=><p key={x.id} className="queued">{x.symptom} · {x.source} · {x.at}</p>)}</section></div></section>}
 {view==='demo'&&<section className="page"><p className="eyebrow">{tx('demoTitle')}</p><h1>{tx('demoHero')}</h1><div className="flow">{['sensor','backend','engine','dashboard','alert','task'].map((x,i)=><div key={x} className={i<5?'flowstep':''}><b>{i+1}</b>{tx(x as any)}</div>)}</div><section className="panel"><h2>{tx('simulator')}</h2><p>{tx('selected')} <strong>{selected.name}</strong>. {tx('raw')}</p><button className="primary" onClick={simulate}>{tx('simulate')}</button><div className="alert"><h3>{tx('preview')}</h3><select value={channel} onChange={e=>setChannel(e.target.value)}><option>SMS</option><option>Voice / IVR</option><option>WhatsApp</option></select><p><b>{channel}</b> → {tx('alertText')}</p></div></section></section>}
 </main> }
const Card=({n,label,red,yellow}:{n:string|number;label:string;red?:boolean;yellow?:boolean})=>{const {number}=useLanguage();return <article className={`card ${red?'red':yellow?'yellow':''}`}><strong>{number(n)}</strong><span>{label}</span></article>};
const Info=({title,value}:{title:string;value:string})=><article className="info"><h3>{title}</h3><b>{value}</b></article>;
const Logo=()=> <svg className="logo" viewBox="0 0 48 48" aria-label="Water safety mark" role="img"><path d="M24 4C16 15 10 21 10 30a14 14 0 0 0 28 0C38 21 32 15 24 4Z" fill="#0070f3" stroke="#000" strokeWidth="3"/><path d="M17 30c2 4 5 6 10 6" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round"/></svg>;
